(setq packages '(evil))

(mapc (lambda (pkg)
        (let ((init-file (concat "~/.emacs.d/inits/" (symbol-name pkg) ".el")))
          (if (not (require pkg nil t))
              (package-install (car mode))
            (if (file-exists-p init-file)
                (eval-after-load (symbol-name pkg) init-file)
              (format "Coult not init %s" init-file)))))
      packages)
